tag: MoeMotion_reg_moe_I

pl_module:
  _target_: realmotion.model.pl_modules.Reg_moe_LightningModule
  total_epochs: ${epochs}
  modes: 6
  k: ${top_k}
  n_step: ${n_step}
  logits_max: True
  history_frames: 50
  schedule_type: 'linear'
  intent_label: ${intent_label}
  model:
    _target_: realmotion.model.moemotion.MoeMotion_I
    embed_dim: 128
    future_steps: ${n_step}
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
    moe: True
    use_transformer_decoder: True
    query_cross_layers: 2
    query_self_atten: True
    query_self_layers: 1
    num_experts: 9
    top_k: ${top_k}
    intent_label: ${intent_label}
  optim:
    lr: 1e-3
    weight_decay: 1e-2
    min_lr: 1e-5
    epochs: ${epochs}
    warmup_ratio: 0.167
