tag: MoeMotion_moe_regres

pl_module:
  _target_: realmotion.model.pl_modules.BaseLightningModule
  model:
    _target_: realmotion.model.moemotion.MoeMotion
    embed_dim: 128
    mlp_dim: 128
    history_len: ${history_len}
    future_steps: ${n_step}
    future_len: ${future_len}
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
    mlp_drop: 0.0
    moe: True
    his_embed_moe: [False, False, False, True]
    moe_type: "intent_regre"
    query_cross_layers: 2
    query_self_atten: True
    query_self_layers: 1
    num_experts: ${num_experts}
    top_k: ${top_k}
    intent_label: ${intent_label}
  optim:
    lr: 2.5e-3
    weight_decay: 1e-2
    min_lr: 1e-5
    epochs: ${epochs}
    warmup_ratio: 0.167
