tag: MoeMotion_reg_I

pl_module:
  _target_: realmotion.model.pl_modules.RegressionLightningModule
  total_epochs: ${epochs}
  modes: 6
  k: ${top_k}
  n_step: ${n_step}
  logits_max: False
  history_frames: 50
  schedule_type: 'linear'
  model:
    _target_: realmotion.model.moemotion.MoeMotion_I
    embed_dim: 128
    future_steps: ${n_step}
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
    moe: False
    use_transformer_decoder: False
    query_self_atten: True
  optim:
    lr: 1e-3
    weight_decay: 1e-2
    min_lr: 1e-5
    epochs: ${epochs}
    warmup_ratio: 0.167
